### ISSUE TITLE
Note taking tools :)

### ISSUE THREAD

**Issue by stenpiren** [visual-ml-notes/visual-machine-learning-notes#1]
Hi Robert,

Your notes are super great. I would like to ask, for the NeuRIPS, which tool(s) did you use to write the notes? Is it iPad Pro? If so, which app and writing stylus did you use? I am curious, would like to get one. Thanks :)

**Comment by prabhuomkar** [comment]
He uses iPad Pro with Apple Pencil and Notability App.
Can you update this in README @RobertTLange ?

**Comment by RobertTLange** [comment]
@stenpiren thank you very much for the kind words. Sorry for the delay! Yes, I just added a [FAQ section to the Readme](https://github.com/visual-ml-notes/visual-machine-learning-notes/commit/bfc4a64d94926b6dbb404e00b887a18faf3bdc14). I hope this helps.
